FROM centos:7.2.1511

LABEL name="CentOS7 Base Image with git" \
    license="MIT" \
    build-date="20170912"

MAINTAINER Li Xipeng <lixipeng@prophetech.cn>

# Install git
RUN yum install -y git

CMD ["/bin/bash"]
