version: '2.0'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - "~/.data/db:/var/lib/mysql"
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - "~/.data/db:/var/lib/mysql"
    restart: always
    ports:
      - "15672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
  keystone:
    image: monasca/keystone:1.1.2
    ports:
      - "5000:5000"
      - "35357:35357"
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
    environment:
      KEYSTONE_USERNAME: admin
      KEYSTONE_PROJECT: admin
      KEYSTONE_PASSWORD: admin_pass
      KEYSTONE_ROLE: admin
      KEYSTONE_REGION: RegionOne
      KEYSTONE_HOST: 192.168.10.102
