FROM lxps/centos7-git:latest

LABEL name="CentOS7 Base Image for dev" \
    license="MIT" \
    build-date="20170912"

MAINTAINER Li Xipeng <lixipeng@prophetech.cn>

# Install git
RUN yum install -y gcc python-devel python-pip

CMD ["/bin/bash"]
